"""users table

Revision ID: 66c348aa42c9
Revises: 
Create Date: 2025-12-02 12:15:38.596855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c348aa42c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=64), nullable=True),
    sa.Column('course', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_course'), ['course'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_student_name'), ['student_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_student_name'))
        batch_op.drop_index(batch_op.f('ix_certificate_course'))

    op.drop_table('certificate')
    # ### end Alembic commands ###
